//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 16.0.29409.12
// 
namespace CiccioGest.Presentation.Uwp.App1.Wcf {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FatturaReadOnly", Namespace="http://gest.cicciosoft.tk")]
    public partial class FatturaReadOnly : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NomeField;
        
        private int TotaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Totale {
            get {
                return this.TotaleField;
            }
            set {
                if ((this.TotaleField.Equals(value) != true)) {
                    this.TotaleField = value;
                    this.RaisePropertyChanged("Totale");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityOfint", Namespace="http://gest.cicciosoft.tk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.DomainEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Articolo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Categoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Fattura))]
    public partial class EntityOfint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainEntity", Namespace="http://gest.cicciosoft.tk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Articolo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Categoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Fattura))]
    public partial class DomainEntity : CiccioGest.Presentation.Uwp.App1.Wcf.EntityOfint {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Articolo", Namespace="http://gest.cicciosoft.tk")]
    public partial class Articolo : CiccioGest.Presentation.Uwp.App1.Wcf.DomainEntity {
        
        private CiccioGest.Presentation.Uwp.App1.Wcf.Categoria CategoriaField;
        
        private string NomeField;
        
        private string NomeCategoriaField;
        
        private int PrezzoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CiccioGest.Presentation.Uwp.App1.Wcf.Categoria Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCategoria {
            get {
                return this.NomeCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeCategoriaField, value) != true)) {
                    this.NomeCategoriaField = value;
                    this.RaisePropertyChanged("NomeCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Prezzo {
            get {
                return this.PrezzoField;
            }
            set {
                if ((this.PrezzoField.Equals(value) != true)) {
                    this.PrezzoField = value;
                    this.RaisePropertyChanged("Prezzo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://gest.cicciosoft.tk")]
    public partial class Categoria : CiccioGest.Presentation.Uwp.App1.Wcf.DomainEntity {
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://gest.cicciosoft.tk")]
    public partial class Cliente : CiccioGest.Presentation.Uwp.App1.Wcf.DomainEntity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fattura", Namespace="http://gest.cicciosoft.tk")]
    public partial class Fattura : CiccioGest.Presentation.Uwp.App1.Wcf.DomainEntity {
        
        private CiccioGest.Presentation.Uwp.App1.Wcf.Dettaglio[] DettagliField;
        
        private string NomeField;
        
        private int TotaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CiccioGest.Presentation.Uwp.App1.Wcf.Dettaglio[] Dettagli {
            get {
                return this.DettagliField;
            }
            set {
                if ((object.ReferenceEquals(this.DettagliField, value) != true)) {
                    this.DettagliField = value;
                    this.RaisePropertyChanged("Dettagli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Totale {
            get {
                return this.TotaleField;
            }
            set {
                if ((this.TotaleField.Equals(value) != true)) {
                    this.TotaleField = value;
                    this.RaisePropertyChanged("Totale");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dettaglio", Namespace="http://gest.cicciosoft.tk")]
    public partial class Dettaglio : CiccioGest.Presentation.Uwp.App1.Wcf.DomainValueObject {
        
        private CiccioGest.Presentation.Uwp.App1.Wcf.Articolo ArticoloField;
        
        private string NomeProdottoField;
        
        private int PrezzoProdottoField;
        
        private int QuantitaField;
        
        private int TotaleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CiccioGest.Presentation.Uwp.App1.Wcf.Articolo Articolo {
            get {
                return this.ArticoloField;
            }
            set {
                if ((object.ReferenceEquals(this.ArticoloField, value) != true)) {
                    this.ArticoloField = value;
                    this.RaisePropertyChanged("Articolo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProdotto {
            get {
                return this.NomeProdottoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeProdottoField, value) != true)) {
                    this.NomeProdottoField = value;
                    this.RaisePropertyChanged("NomeProdotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrezzoProdotto {
            get {
                return this.PrezzoProdottoField;
            }
            set {
                if ((this.PrezzoProdottoField.Equals(value) != true)) {
                    this.PrezzoProdottoField = value;
                    this.RaisePropertyChanged("PrezzoProdotto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Totale {
            get {
                return this.TotaleField;
            }
            set {
                if ((this.TotaleField.Equals(value) != true)) {
                    this.TotaleField = value;
                    this.RaisePropertyChanged("Totale");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueObjectOfint", Namespace="http://gest.cicciosoft.tk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.DomainValueObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Dettaglio))]
    public partial class ValueObjectOfint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainValueObject", Namespace="http://gest.cicciosoft.tk")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CiccioGest.Presentation.Uwp.App1.Wcf.Dettaglio))]
    public partial class DomainValueObject : CiccioGest.Presentation.Uwp.App1.Wcf.ValueObjectOfint {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wcf.IFatturaService")]
    public interface IFatturaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/GetFatture", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/GetFattureResponse")]
        System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.FatturaReadOnly[]> GetFattureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/GetFattura", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/GetFatturaResponse")]
        System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Fattura> GetFatturaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/SaveFattura", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/SaveFatturaResponse")]
        System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Fattura> SaveFatturaAsync(CiccioGest.Presentation.Uwp.App1.Wcf.Fattura fattura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/DeleteFattura", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/DeleteFatturaResponse")]
        System.Threading.Tasks.Task DeleteFatturaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/GetArticolo", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/GetArticoloResponse")]
        System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Articolo> GetArticoloAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gest.cicciosoft.tk/IFatturaService/GetCliente", ReplyAction="http://gest.cicciosoft.tk/IFatturaService/GetClienteResponse")]
        System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Cliente> GetClienteAsync(int idCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFatturaServiceChannel : CiccioGest.Presentation.Uwp.App1.Wcf.IFatturaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FatturaServiceClient : System.ServiceModel.ClientBase<CiccioGest.Presentation.Uwp.App1.Wcf.IFatturaService>, CiccioGest.Presentation.Uwp.App1.Wcf.IFatturaService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FatturaServiceClient() : 
                base(FatturaServiceClient.GetDefaultBinding(), FatturaServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFatturaService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FatturaServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FatturaServiceClient.GetBindingForEndpoint(endpointConfiguration), FatturaServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FatturaServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FatturaServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FatturaServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FatturaServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FatturaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.FatturaReadOnly[]> GetFattureAsync() {
            return base.Channel.GetFattureAsync();
        }
        
        public System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Fattura> GetFatturaAsync(int id) {
            return base.Channel.GetFatturaAsync(id);
        }
        
        public System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Fattura> SaveFatturaAsync(CiccioGest.Presentation.Uwp.App1.Wcf.Fattura fattura) {
            return base.Channel.SaveFatturaAsync(fattura);
        }
        
        public System.Threading.Tasks.Task DeleteFatturaAsync(int id) {
            return base.Channel.DeleteFatturaAsync(id);
        }
        
        public System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Articolo> GetArticoloAsync(int id) {
            return base.Channel.GetArticoloAsync(id);
        }
        
        public System.Threading.Tasks.Task<CiccioGest.Presentation.Uwp.App1.Wcf.Cliente> GetClienteAsync(int idCliente) {
            return base.Channel.GetClienteAsync(idCliente);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFatturaService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFatturaService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/FatturaService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return FatturaServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFatturaService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return FatturaServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFatturaService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IFatturaService,
        }
    }
}
